### ISSUE TITLE
anova() for clmm objects doesn’t work inside functions (looks for objects in the wrong env?)

### ISSUE THREAD

**Issue by huftis** [runehaubo/ordinal#38] opened 2020-11-11 13:11 UTC
Inside a function, `anova.clmm()` doesn’t work properly. I think it looks for the objects in the wrong environment (the global one), so it uses the wrong objects (if similarly named global objects exist) or exists with an error (if they don’t). Here’s a simple reprex:

First I simulate five datasets:

```r
library(ordinal)

# Simulate a simple data sett
simulate = function(n = 100) {
  y = ordered(sample(1:5, n, replace = TRUE))
  x = runif(n)
  gr = sample(1:10, n, replace =TRUE)
  data.frame(y, x, gr)
}

# Simulate 5 datasets
set.seed(123)
l_data = replicate(5, simulate(), simplify = FALSE)
```

Analysing one of the datasets works fine:

```r
# Analyse the first dataset manually
# and extract the p value of the x coefficient
d = l_data[[1]]
mod0 = clmm(y ~ 1 + (1|gr), data = d)
mod1 = update(mod0, . ~ x + (1|gr))
p = anova(mod0, mod1)$`Pr(>Chisq)`[2]
p # OK
#> [1] 0.2188232
```

But I want to easily analyse all of them, so I write a function:

```r
get_p_val = function(d) {
  mod0 = clmm(y ~ 1 + (1|gr), data = d)
  mod1 = update(mod0, . ~ x + (1|gr))
  p = anova(mod0, mod1)$`Pr(>Chisq)`[2]
  p
}
```

Calling the function seemingly works fine for the first dataset. But in fact, it uses the model objects from the global environment instead of the ones fitted inside the function. So we get the same *P*-value for all datasets:

```r
get_p_val(l_data[[1]]) # *Looks* OK (but isn’t)
#> [1] 0.2188232
get_p_val(l_data[[2]]) # Wrong P-value (same as above)
#> [1] 0.2188232
get_p_val(l_data[[3]]) # Still the wrong P-value + strange warning
#> Warning in update.uC(rho): Non finite negative log-likelihood
#>   at iteration 26
#> [1] 0.2188232
```

Note that for `l_data[[3]]`, there is an additional warning (which I guess is from fitting one of the models for the third data set).

I would typically use the `get_p_val()` function like this:

```r
lapply(l_data, get_p_val) # Identical P-values
#> Warning in update.uC(rho): Non finite negative log-likelihood
#>   at iteration 26
#> [[1]]
#> [1] 0.2188232
#> 
#> [[2]]
#> [1] 0.2188232
#> 
#> [[3]]
#> [1] 0.2188232
#> 
#> [[4]]
#> [1] 0.2188232
#> 
#> [[5]]
#> [1] 0.2188232
```

It is easy to see that the function uses the global variables, since we get an error message if we remove one of them:

```r
rm(mod1)
get_p_val(l_data[[3]])
#> Warning in update.uC(rho): Non finite negative log-likelihood
#>   at iteration 26
#> Error in (function (object, ..., type = c("I", "II", "III", "1", "2", : object 'mod1' not found
```

Also note that the `anova()` function for `clm` models does *not* have this problem. You can easily test this by just replacing `clmm` with `clm` in the code above.

**Comment by JackEdTaylor** [comment] 2021-08-19 08:04
# A quick fix

I had the same problem. A quick solution until there is a proper fix is to use `ordinal:::anova.clm()` in the function instead of `anova()`. Using the datasets you simulate:

```
get_p_val <- function(d) {
  mod0 <- clmm(y ~ 1 + (1|gr), data = d)
  mod1 <- update(mod0, . ~ x + (1|gr))
  # use ordinal:::anova.clm() to avoid the environments issue
  p <- ordinal:::anova.clm(mod0, mod1)$`Pr(>Chisq)`[2]
  p
}
```

Now the function gives the correct p values for each object separately:

```
lapply(l_data, get_p_val)

# [[1]]
# [1] 0.2188232
# 
# [[2]]
# [1] 0.5233834
# 
# [[3]]
# [1] 0.1359248
# 
# [[4]]
# [1] 0.01214862
# 
# [[5]]
# [1] 0.6363212
```

# Why does the error occur?

The problem is that because `anova.clmm()` is a wrapper for `anova.clm()`, `ordinal` uses `match.call()` to make sure the names in the summary are correct  (see [here](https://github.com/runehaubo/ordinal/blob/6b279bfc7aed755bf4647de3cd6faf4da1ef282e/R/clmm.methods.R#L228)). Without this, `anova.clmm()` would show the wrong names for the objects when the anova summary is printed:

```
d <- l_data[[1]]
mod0 <- clmm(y ~ 1 + (1|gr), data = d)
mod1 <- update(mod0, . ~ x + (1|gr))
dummy_anova.clmm <- function(object, ...) {
  ordinal:::anova.clm(object, ...)
}
dummy_anova.clmm(mod0, mod1)

# Likelihood ratio tests of cumulative link models:
#   
#   formula:         link: threshold:
#   object y ~ 1 + (1 | gr) logit flexible  
# ..1    y ~ x + (1 | gr) logit flexible  
# 
# no.par    AIC  logLik LR.stat df Pr(>Chisq)
# object      5 330.88 -160.44                      
# ..1         6 331.37 -159.69  1.5121  1     0.2188
```

`object` and `..1` are shown as the model names, rather than `mod0` and `mod1`, because by wrapping it, `anova.clm()` now uses the function's names for the objects (`object` and ellipsis).

`match.call()` usually works because it "returns a call in which all of the specified arguments are specified by their full names". The problem is that it assumes the objects you're looking up are in the global environment. This exact issue actually comes up in the book, Advanced R: http://adv-r.had.co.nz/Expressions.html#capturing-call.

# A proper fix

Similar to the solution in Advanced R, a fix could specify which environment to use for the `do.call()`. Something like this would work:

```
fixed_anova.clmm <- function(object, ...) {
  mc <- match.call()
  arg.list <- as.list(mc)
  arg.list[[1]] <- NULL
  return(do.call(ordinal:::anova.clm, arg.list, envir = environment(formula(object))))
}
```

Now, `fixed.anova.clmm()` gives us this for comparing `mod0` and `mod1`, with the correct model names in the summary:

```
fixed_anova.clmm(mod0, mod1)

# Likelihood ratio tests of cumulative link models:
#   
#   formula:         link: threshold:
#   mod0 y ~ 1 + (1 | gr) logit flexible  
# mod1 y ~ x + (1 | gr) logit flexible  
# 
# no.par    AIC  logLik LR.stat df Pr(>Chisq)
# mod0      5 330.88 -160.44                      
# mod1      6 331.37 -159.69  1.5121  1     0.2188
```

But it is also happy to be nested in a function:

```
get_p_val <- function(d) {
  mod0 <- clmm(y ~ 1 + (1|gr), data = d)
  mod1 <- update(mod0, . ~ x + (1|gr))
  # use ordinal:::anova.clm to avoid the environments issue
  p <- fixed_anova.clmm(mod0, mod1)$`Pr(>Chisq)`[2]
  p
}

lapply(l_data, get_p_val)

# [[1]]
# [1] 0.2188232
# 
# [[2]]
# [1] 0.5233834
# 
# [[3]]
# [1] 0.1359248
# 
# [[4]]
# [1] 0.01214862
# 
# [[5]]
# [1] 0.6363212
```

**Comment by runehaubo** [comment] 2021-08-19 08:13
Thanks Jack for your analysis and suggestions! I think you are spot on and
I will implement and test as soon as possible (though I'm busy with other
stuff right now... sigh.) A quick note is that
'environment(formula(object))' may not always be enough to grab the right
environment. There is code in lmerTest (which I wrote and I think the fix
should apply here as well) that tries several environments to evaluate the
data/model - I just hadn't thought of it here ;-)

Cheers
Rune

**Comment by runehaubo** [comment] 2022-11-13 14:14
Thanks again. This is now fixed.

**Closed by runehaubo** 2022-11-13 14:14 UTC
