### ISSUE TITLE
Error in x$code == 0L || action == "silent": 'length = 2' in coercion to 'logical(1)'

### ISSUE THREAD

**Issue by 3timen** [runehaubo/ordinal#59] opened 2023-07-12 13:53 UTC
I was trying to run a simple clm() until I got the above mentioned error.
I think this error is caused by the change in R 4.2 as explained in [this post](https://stackoverflow.com/questions/72848442/r-warning-lengthx-2-1-in-coercion-to-logical1)

**Comment by runehaubo** [comment] 2023-07-14 10:18
Is this with the current version of ordinal - I should have fixed those
cases. If updating does not solve it, please report your sessionInfo() in a
follow-up report.

Cheers
Rune

**Comment by SimonShamusRiley** [comment] 2024-04-12 16:22
Hello,

I seem to be encountering the same issue. As per your discussion with 3timin, I first uninstalled the package and reinstalled via:
>devtools::install_github('runehaubo/ordinal')

but that didn't solve the problem, so below I've provided session info. If you need me to put together a reproducible example I can do that as well. Thanks in advance.

> fit = clm(Flushing ~ Cultivar*ObsDay, data = flush)

Error in x$code == 0L || action == "silent" : 
  'length = 2' in coercion to 'logical(1)'

> sessionInfo()

R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] extrafont_0.19    ordinal_2023.12-4 emmeans_1.10.0    lubridate_1.9.3   forcats_1.0.0    
 [6] stringr_1.5.1     dplyr_1.1.4       purrr_1.0.2       readr_2.1.5       tidyr_1.3.1      
[11] tibble_3.2.1      ggplot2_3.4.4     tidyverse_2.0.0   readxl_1.4.3     

loaded via a namespace (and not attached):
 [1] gtable_0.3.4        htmlwidgets_1.6.4   devtools_2.4.5      remotes_2.4.2.1     processx_3.8.3     
 [6] lattice_0.21-9      numDeriv_2016.8-1.1 callr_3.7.3         tzdb_0.4.0          vctrs_0.6.5        
[11] tools_4.3.2         ps_1.7.6            generics_0.1.3      sandwich_3.1-0      curl_5.2.0         
[16] fansi_1.0.6         ucminf_1.2.1        pkgconfig_2.0.3     Matrix_1.6-5        desc_1.4.3         
[21] rematch_2.0.0       lifecycle_1.0.4     compiler_4.3.2      munsell_0.5.0       codetools_0.2-19   
[26] httpuv_1.6.14       htmltools_0.5.7     usethis_2.2.2       Rttf2pt1_1.3.12     extrafontdb_1.0    
[31] later_1.3.2         pillar_1.9.0        urlchecker_1.0.1    MASS_7.3-60         ellipsis_0.3.2     
[36] cachem_1.0.8        sessioninfo_1.2.2   multcomp_1.4-25     nlme_3.1-163        mime_0.12          
[41] tidyselect_1.2.0    digest_0.6.34       mvtnorm_1.2-4       stringi_1.8.3       splines_4.3.2      
[46] fastmap_1.1.1       grid_4.3.2          colorspace_2.1-0    cli_3.6.2           magrittr_2.0.3     
[51] survival_3.5-7      pkgbuild_1.4.3      utf8_1.2.4          TH.data_1.1-2       withr_3.0.0        
[56] scales_1.3.0        promises_1.2.1      timechange_0.3.0    estimability_1.4.1  cellranger_1.1.0   
[61] zoo_1.8-12          hms_1.1.3           memoise_2.0.1       coda_0.19-4.1       shiny_1.8.0        
[66] miniUI_0.1.1.1      profvis_0.3.8       rlang_1.1.3         Rcpp_1.0.12         xtable_1.8-4       
[71] glue_1.7.0          pkgload_1.3.4       rstudioapi_0.15.0   R6_2.5.1            fs_1.6.3

**Comment by AnahiEspindola** [comment] 2024-08-20 20:12
I am also running into this issue. I had a dataset that I had analyzed with clm a couple months ago and the function worked great. Now I had to slightly edit the data (remove some points), but when I tried to run the exact same code it threw that error.  Since I last run the code, I had to update my R version and all the packages, so I am very suspicious that this is the problem (and not my data, which has basically not changed).

What I am running is a very simple line:
CLMSpAllYears=clm(as.factor(Quantity)~Year, data=AllNewDataDFS1S3, link = c("logit"),
              threshold = c("flexible"))
              
The error is
Error in x$code == 0L || action == "silent" : 
  'length = 2' in coercion to 'logical(1)'

When I check sessionInfo(), this is what I get.

> sessionInfo()
R version 4.4.1 (2024-06-14 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 22631)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ordinal_2023.12-4 MASS_7.3-60.2     raster_3.6-26     sp_2.1-4          spatial_7.3-17    lubridate_1.9.3  
 [7] forcats_1.0.0     stringr_1.5.1     dplyr_1.1.4       purrr_1.0.2       readr_2.1.5       tidyr_1.3.1      
[13] tibble_3.2.1      tidyverse_2.0.0   reshape2_1.4.4    ggplot2_3.5.1    

loaded via a namespace (and not attached):
 [1] Matrix_1.7-0        gtable_0.3.5        ucminf_1.2.2        compiler_4.4.1      tidyselect_1.2.1   
 [6] Rcpp_1.0.13         scales_1.3.0        lattice_0.22-6      R6_2.5.1            plyr_1.8.9         
[11] labeling_0.4.3      generics_0.1.3      munsell_0.5.1       pillar_1.9.0        tzdb_0.4.0         
[16] rlang_1.1.4         utf8_1.2.4          stringi_1.8.4       terra_1.7-78        timechange_0.3.0   
[21] cli_3.6.3           withr_3.0.1         magrittr_2.0.3      grid_4.4.1          rstudioapi_0.16.0  
[26] hms_1.1.3           nlme_3.1-164        lifecycle_1.0.4     vctrs_0.6.5         glue_1.7.0         
[31] farver_2.1.2        numDeriv_2016.8-1.1 codetools_0.2-20    fansi_1.0.6         colorspace_2.1-1   
[36] tools_4.4.1         pkgconfig_2.0.3    

Any ideas of what the problem may be? Thanks!

**Comment by mfeinleib-hart** [comment] 2024-10-22 19:17
Also having this issue. The variable that causes it for me (`registration_year`) is an integer, although converting it to a double doesn't fix anything. There are other integer variables in my models that work fine.

Here is a reduced example:

```
> str(mini_data)

tibble [2,995 × 4] (S3: tbl_df/tbl/data.frame)
 $ pres_vote        : Ord.factor w/ 7 levels "Trump"<"Trump (lean)"<..: 7 1 1 7 1 7 1 7 1 3 ...
 $ survey_mode      : Factor w/ 2 levels "Phone","Online": 2 2 2 2 2 2 2 2 2 2 ...
 $ state            : Factor w/ 10 levels "AZ","GA","MI",..: 9 7 7 3 1 8 9 6 1 7 ...
 $ registration_year: int [1:2995] 2022 2024 2024 2024 2024 2020 2023 2024 2024 2024 ...


> ordinal::clm(pres_vote ~ survey_mode + registration_year,
+              data = mini_data)

Error in x$code == 0L || action == "silent" : 
  'length = 2' in coercion to 'logical(1)'
```

**Comment by feinleib** [comment] 2024-10-22 19:19
Also having this issue. The variable that causes it for me (`registration_year`) is an integer, although converting it to a double doesn't fix anything. There are other integer variables in my models that work fine.

Here is a reduced example:

```
> str(mini_data)

tibble [2,995 × 4] (S3: tbl_df/tbl/data.frame)
 $ pres_vote        : Ord.factor w/ 7 levels "Trump"<"Trump (lean)"<..: 7 1 1 7 1 7 1 7 1 3 ...
 $ survey_mode      : Factor w/ 2 levels "Phone","Online": 2 2 2 2 2 2 2 2 2 2 ...
 $ state            : Factor w/ 10 levels "AZ","GA","MI",..: 9 7 7 3 1 8 9 6 1 7 ...
 $ registration_year: int [1:2995] 2022 2024 2024 2024 2024 2020 2023 2024 2024 2024 ...


> ordinal::clm(pres_vote ~ survey_mode + registration_year,
+              data = mini_data)

Error in x$code == 0L || action == "silent" : 
  'length = 2' in coercion to 'logical(1)'
```

**Comment by nas258** [comment] 2024-12-13 18:48
Are there any updates on this thread?
Seems to have closed but others including myself are still receiving the issue:
"Error in x$code == 0L || action == "silent" : 
  'length = 2' in coercion to 'logical(1)'"

My model is also very simple:
model1 <- clm(Lodging..Rating.Plot.~Crop.Density..plants.with.pods.ha.,
              data = LodgRate.bbDen.VTsite,
              link = "logit")

**Comment by nas258** [comment] 2024-12-13 19:08
After doing some playing around with my variables, I realized (in my case), that the error was happening because my "Crop.Density..plants.with.pods.ha." values were too large (ranging from 100,000 to 800,000 plants/ha). Once I divided the value by 1000, the model began to run.

**Comment by runehaubo** [comment] 2024-12-13 20:04
Please send your sessionInfo() ;-)

fre. 13. dec. 2024 kl. 20.08 skrev Nazir (Adam) Sharifi <
***@***.***>:

**Comment by nas258** [comment] 2024-12-13 20:10
> sessionInfo()
R version 4.4.1 (2024-06-14 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 22631)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lubridate_1.9.4     forcats_1.0.0       stringr_1.5.1       purrr_1.0.2         readr_2.1.5         tidyr_1.3.1         tibble_3.2.1        tidyverse_2.0.0     cowplot_1.1.3       nlme_3.1-166       
[11] nls.multstart_1.3.0 ggfortify_0.4.17    performance_0.12.4  MuMIn_1.48.4        lmerTest_3.1-3      lme4_1.1-35.5       Matrix_1.7-1        DHARMa_0.4.7        nlstools_2.1-0      dplyr_1.1.4        
[21] ggplot2_3.5.1       ordinal_2023.12-4.1

loaded via a namespace (and not attached):
 [1] utf8_1.2.4        generics_0.1.3    stringi_1.8.4     lattice_0.22-6    hms_1.1.3         magrittr_2.0.3    timechange_0.3.0  grid_4.4.1        gridExtra_2.3     fansi_1.0.6       scales_1.3.0      numDeriv_2022.9-1
[13] cli_3.6.3         rlang_1.1.4       munsell_0.5.1     splines_4.4.1     withr_3.0.2       tools_4.4.1       ucminf_1.2.2      tzdb_0.4.0        nloptr_2.1.1      minqa_1.2.8       colorspace_2.1-1  boot_1.3-31      
[25] vctrs_0.6.5       R6_2.5.1          stats4_4.4.1      lifecycle_1.0.4   MASS_7.3-61       insight_1.0.0     pkgconfig_2.0.3   pillar_1.9.0      gtable_0.3.6      glue_1.7.0        Rcpp_1.0.13-1     tidyselect_1.2.1 
[37] rstudioapi_0.17.1 compiler_4.4.1

**Comment by runehaubo** [comment] 2024-12-13 22:42
I think I have fixed this now in the version on github - could you check if it also works for you? (eg. using something like `remotes::install_github("runehaubo/ordinal")`)

**Comment by nas258** [comment] 2024-12-14 01:38
Could you please be more specific on what you have fixed?

**This is the output I got from running the code in the console:**
> remotes::install_github("runehaubo/ordinal")
Using GitHub PAT from the git credential store.
Downloading GitHub repo runehaubo/ordinal@HEAD
Skipping 1 packages ahead of CRAN: numDeriv
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\#####\AppData\Local\Temp\######\#######33\runehaubo-ordinal-59ba5b5/DESCRIPTION' ...
─  preparing 'ordinal': (1.5s)
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building 'ordinal_2024.12-13.tar.gz'
   
Installing package into ‘C:/Users/#####/AppData/Local/R/win-library/4.4’
(as ‘lib’ is unspecified)
* installing *source* package 'ordinal' ...
** using staged installation
** libs
using C compiler: 'gcc.exe (GCC) 13.3.0'
gcc  -I"C:/PROGRA~1/R/R-44~1.1/include" -DNDEBUG     -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c get_fitted.c -o get_fitted.o
gcc  -I"C:/PROGRA~1/R/R-44~1.1/include" -DNDEBUG     -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c init.c -o init.o
gcc  -I"C:/PROGRA~1/R/R-44~1.1/include" -DNDEBUG     -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c links.c -o links.o
gcc  -I"C:/PROGRA~1/R/R-44~1.1/include" -DNDEBUG     -I"c:/rtools44/x86_64-w64-mingw32.static.posix/include"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c utilityFuns.c -o utilityFuns.o
gcc -shared -s -static-libgcc -o ordinal.dll tmp.def get_fitted.o init.o links.o utilityFuns.o -Lc:/rtools44/x86_64-w64-mingw32.static.posix/lib/x64 -Lc:/rtools44/x86_64-w64-mingw32.static.posix/lib -LC:/PROGRA~1/R/R-44~1.1/bin/x64 -lR
installing to C:/Users/#####/AppData/Local/R/win-library/4.4/00LOCK-ordinal/00new/ordinal/libs/x64
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Warning in file.rename(instdir, final_instdir) :
  cannot rename file 'C:/Users/#####/AppData/Local/R/win-library/4.4/00LOCK-ordinal/00new/ordinal' to 'C:/Users/###/AppData/Local/R/win-library/4.4/ordinal', reason 'Access is denied'
ERROR:    moving to final location failed
* removing 'C:/Users/####/AppData/Local/R/win-library/4.4/ordinal'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/###/AppData/Local/Temp/RtmpEhRsU9/file2cec1c253193/ordinal_2024.12-13.tar.gz’ had non-zero exit status

**Comment by runehaubo** [comment] 2024-12-14 09:21
It's the bug that has been fixed which caused this error: 
```
Error in x$code == 0L || action == "silent" : 
  'length = 2' in coercion to 'logical(1)'
```
You seem to be on Windows and having problems compiling the package and/or access/rights problems. If you download this Windows zip-binary of the package you should be able to "install from local zip file". I would be grateful if you could check if the error goes away with the new package version (though you should get a warning) on the original data.

Cheers
Rune
[ordinal_2024.12-13.zip](https://github.com/user-attachments/files/18135248/ordinal_2024.12-13.zip)

**Comment by nas258** [comment] 2024-12-14 17:00
A success I believe! Thank you for your hard work.

However, should I be concerned about the warning message? I am using large values but these are the acceptable units for my field's for publication.

> model1 <- clm(Lodging..Rating.Plot.~Crop.Density..plants.with.pods.ha.,
+               data = LodgRate.bbDen.VT22site,
+               link = "logit")
Warning message:
(2) Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables? 
In addition: Absolute and relative convergence criteria were met

**Comment by runehaubo** [comment] 2024-12-14 17:43
Great! Thanks for confirming. 

Yes, you should pay attention to the warning message which tells you that you are working on the boundary of the numerical accuracy of your computer. It may, or may not, affect the precision of the coefficient or its standard error in your particular case. In any case you already did the right thing: you rescaled the offending variable. Ideally it should be scaled such that the coefficient is between 0.1 and 10 - this leads the most stable computations. Once the model is fitted you simply re-rescale the coefficient and its standard error by the same factor if the original units are particularly meaningful; the model remains the same. For further details check out the clm-vignette.

Cheers
Rune

**Closed by runehaubo** 2024-12-14 17:43 UTC

**Comment by mfeinleib-hart** [comment] 2024-12-14 18:26
Confirming that this fixed the error - thanks!

I think you could make the warning message more informative, though.
```
Warning message:
(2) Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables? 
In addition: Absolute and relative convergence criteria were met
```
Some portion of your tip above would be useful to users who don't know (1) what this means and (2) what to do about it. The part about scaling to around the [0.1, 10] range (and how to rescale afterward) is especially informative. Pointing users to the vignette for more info also seems like a good idea.

> Yes, you should pay attention to the warning message which tells you that you are working on the boundary of the numerical accuracy of your computer. It may, or may not, affect the precision of the coefficient or its standard error in your particular case. [...] Ideally it should be scaled such that the coefficient is between 0.1 and 10 - this leads the most stable computations. Once the model is fitted you simply re-rescale the coefficient and its standard error by the same factor if the original units are particularly meaningful; the model remains the same. For further details check out the clm-vignette.

-----
In my case (`registration_year` was between `2020` and `2024`), the scaling didn't affect the coefficients (well, just the threshold coefficients `Trump|Trump (lean)` etc., but I didn't care about those values) or model performance. So I would also mention that this mostly impact the threshold coefficients (if that's generally true. I'm just going off my example.).

**Comment by feinleib** [comment] 2024-12-14 18:27
Confirming that this fixed the error - thanks!

I think you could make the warning message more informative, though.
```
Warning message:
(2) Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables? 
In addition: Absolute and relative convergence criteria were met
```
Some portion of your tip above would be useful to users who don't know (1) what this means and (2) what to do about it. The part about scaling to around the [0.1, 10] range (and how to rescale afterward) is especially informative. Pointing users to the vignette for more info also seems like a good idea.

> Yes, you should pay attention to the warning message which tells you that you are working on the boundary of the numerical accuracy of your computer. It may, or may not, affect the precision of the coefficient or its standard error in your particular case. [...] Ideally it should be scaled such that the coefficient is between 0.1 and 10 - this leads the most stable computations. Once the model is fitted you simply re-rescale the coefficient and its standard error by the same factor if the original units are particularly meaningful; the model remains the same. For further details check out the clm-vignette.

-----
In my case (`registration_year` was between `2020` and `2024`), the scaling didn't affect the coefficients (well, just the threshold coefficients `Trump|Trump (lean)` etc., but I didn't care about those values) or model performance. So I would also mention that this mostly impact the threshold coefficients (if that's generally true. I'm just going off my example.).
